// This file is generated from the SQL migrations in supabase/migrations.
// Do not edit it by hand. Run `npm run db:types` after changing the schema.

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

export interface Database {
  public: {
    Tables: {
      organizations: {
        Row: {
          id: string;
          name: string;
          slug: string;
          legal_name: string | null;
          status: Database["public"]["Enums"]["organization_status"];
          timezone: string;
          contact_email: string | null;
          metadata: Json;
          effective_from: string | null;
          effective_to: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          slug: string;
          legal_name?: string | null;
          status?: Database["public"]["Enums"]["organization_status"];
          timezone?: string;
          contact_email?: string | null;
          metadata?: Json;
          effective_from?: string | null;
          effective_to?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          slug?: string;
          legal_name?: string | null;
          status?: Database["public"]["Enums"]["organization_status"];
          timezone?: string;
          contact_email?: string | null;
          metadata?: Json;
          effective_from?: string | null;
          effective_to?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      service_lines: {
        Row: {
          id: string;
          organization_id: string;
          facility_id: string | null;
          code: string;
          name: string;
          description: string | null;
          status: Database["public"]["Enums"]["organization_status"];
          metadata: Json;
          effective_from: string | null;
          effective_to: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          organization_id: string;
          facility_id?: string | null;
          code: string;
          name: string;
          description?: string | null;
          status?: Database["public"]["Enums"]["organization_status"];
          metadata?: Json;
          effective_from?: string | null;
          effective_to?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          organization_id?: string;
          facility_id?: string | null;
          code?: string;
          name?: string;
          description?: string | null;
          status?: Database["public"]["Enums"]["organization_status"];
          metadata?: Json;
          effective_from?: string | null;
          effective_to?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      facilities: {
        Row: {
          id: string;
          organization_id: string;
          service_line_id: string | null;
          code: string;
          name: string;
          facility_type: string | null;
          status: Database["public"]["Enums"]["organization_status"];
          timezone: string;
          address_line_1: string | null;
          address_line_2: string | null;
          city: string | null;
          state_region: string | null;
          postal_code: string | null;
          country_code: string | null;
          metadata: Json;
          effective_from: string | null;
          effective_to: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          organization_id: string;
          service_line_id?: string | null;
          code: string;
          name: string;
          facility_type?: string | null;
          status?: Database["public"]["Enums"]["organization_status"];
          timezone?: string;
          address_line_1?: string | null;
          address_line_2?: string | null;
          city?: string | null;
          state_region?: string | null;
          postal_code?: string | null;
          country_code?: string | null;
          metadata?: Json;
          effective_from?: string | null;
          effective_to?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          organization_id?: string;
          service_line_id?: string | null;
          code?: string;
          name?: string;
          facility_type?: string | null;
          status?: Database["public"]["Enums"]["organization_status"];
          timezone?: string;
          address_line_1?: string | null;
          address_line_2?: string | null;
          city?: string | null;
          state_region?: string | null;
          postal_code?: string | null;
          country_code?: string | null;
          metadata?: Json;
          effective_from?: string | null;
          effective_to?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      departments: {
        Row: {
          id: string;
          organization_id: string;
          facility_id: string;
          service_line_id: string | null;
          parent_department_id: string | null;
          code: string;
          name: string;
          description: string | null;
          status: Database["public"]["Enums"]["organization_status"];
          metadata: Json;
          effective_from: string | null;
          effective_to: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          organization_id: string;
          facility_id: string;
          service_line_id?: string | null;
          parent_department_id?: string | null;
          code: string;
          name: string;
          description?: string | null;
          status?: Database["public"]["Enums"]["organization_status"];
          metadata?: Json;
          effective_from?: string | null;
          effective_to?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          organization_id?: string;
          facility_id?: string;
          service_line_id?: string | null;
          parent_department_id?: string | null;
          code?: string;
          name?: string;
          description?: string | null;
          status?: Database["public"]["Enums"]["organization_status"];
          metadata?: Json;
          effective_from?: string | null;
          effective_to?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      roles: {
        Row: {
          id: string;
          organization_id: string | null;
          name: string;
          slug: string;
          description: string | null;
          scope_level: Database["public"]["Enums"]["scope_level"];
          is_system: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          organization_id?: string | null;
          name: string;
          slug: string;
          description?: string | null;
          scope_level?: Database["public"]["Enums"]["scope_level"];
          is_system?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          organization_id?: string | null;
          name?: string;
          slug?: string;
          description?: string | null;
          scope_level?: Database["public"]["Enums"]["scope_level"];
          is_system?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      permissions: {
        Row: {
          id: string;
          code: string;
          name: string;
          feature_area: string;
          description: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          code: string;
          name: string;
          feature_area: string;
          description?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          code?: string;
          name?: string;
          feature_area?: string;
          description?: string | null;
          created_at?: string;
        };
        Relationships: [];
      };
      role_permissions: {
        Row: {
          role_id: string;
          permission_id: string;
          created_at: string;
        };
        Insert: {
          role_id: string;
          permission_id: string;
          created_at?: string;
        };
        Update: {
          role_id?: string;
          permission_id?: string;
          created_at?: string;
        };
        Relationships: [];
      };
      profiles: {
        Row: {
          id: string;
          organization_id: string | null;
          full_name: string | null;
          work_email: string | null;
          title: string | null;
          status: Database["public"]["Enums"]["user_account_status"];
          phone_number: string | null;
          mfa_required: boolean;
          last_sign_in_at: string | null;
          invited_by: string | null;
          metadata: Json;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id: string;
          organization_id?: string | null;
          full_name?: string | null;
          work_email?: string | null;
          title?: string | null;
          status?: Database["public"]["Enums"]["user_account_status"];
          phone_number?: string | null;
          mfa_required?: boolean;
          last_sign_in_at?: string | null;
          invited_by?: string | null;
          metadata?: Json;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          organization_id?: string | null;
          full_name?: string | null;
          work_email?: string | null;
          title?: string | null;
          status?: Database["public"]["Enums"]["user_account_status"];
          phone_number?: string | null;
          mfa_required?: boolean;
          last_sign_in_at?: string | null;
          invited_by?: string | null;
          metadata?: Json;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      user_role_assignments: {
        Row: {
          id: string;
          organization_id: string;
          user_id: string;
          role_id: string;
          scope_level: Database["public"]["Enums"]["scope_level"];
          facility_id: string | null;
          department_id: string | null;
          service_line_id: string | null;
          assigned_by: string | null;
          starts_at: string;
          ends_at: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          organization_id: string;
          user_id: string;
          role_id: string;
          scope_level?: Database["public"]["Enums"]["scope_level"];
          facility_id?: string | null;
          department_id?: string | null;
          service_line_id?: string | null;
          assigned_by?: string | null;
          starts_at?: string;
          ends_at?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          organization_id?: string;
          user_id?: string;
          role_id?: string;
          scope_level?: Database["public"]["Enums"]["scope_level"];
          facility_id?: string | null;
          department_id?: string | null;
          service_line_id?: string | null;
          assigned_by?: string | null;
          starts_at?: string;
          ends_at?: string | null;
          created_at?: string;
        };
        Relationships: [];
      };
      user_facility_assignments: {
        Row: {
          id: string;
          user_id: string;
          facility_id: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          facility_id: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          facility_id?: string;
          created_at?: string;
        };
        Relationships: [];
      };
      user_department_assignments: {
        Row: {
          id: string;
          user_id: string;
          department_id: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          department_id: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          department_id?: string;
          created_at?: string;
        };
        Relationships: [];
      };
      data_sources: {
        Row: {
          id: string;
          organization_id: string;
          name: string;
          source_type: Database["public"]["Enums"]["data_source_type"];
          vendor_name: string | null;
          description: string | null;
          connection_status: Database["public"]["Enums"]["connection_status"];
          credential_reference: string | null;
          config: Json;
          is_active: boolean;
          last_synced_at: string | null;
          created_by: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          organization_id: string;
          name: string;
          source_type: Database["public"]["Enums"]["data_source_type"];
          vendor_name?: string | null;
          description?: string | null;
          connection_status?: Database["public"]["Enums"]["connection_status"];
          credential_reference?: string | null;
          config?: Json;
          is_active?: boolean;
          last_synced_at?: string | null;
          created_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          organization_id?: string;
          name?: string;
          source_type?: Database["public"]["Enums"]["data_source_type"];
          vendor_name?: string | null;
          description?: string | null;
          connection_status?: Database["public"]["Enums"]["connection_status"];
          credential_reference?: string | null;
          config?: Json;
          is_active?: boolean;
          last_synced_at?: string | null;
          created_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      integration_configurations: {
        Row: {
          id: string;
          organization_id: string;
          data_source_id: string;
          version: number;
          frequency: Database["public"]["Enums"]["schedule_frequency"];
          cron_expression: string | null;
          validation_config: Json;
          error_handling_config: Json;
          is_active: boolean;
          last_tested_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          organization_id: string;
          data_source_id: string;
          version?: number;
          frequency?: Database["public"]["Enums"]["schedule_frequency"];
          cron_expression?: string | null;
          validation_config?: Json;
          error_handling_config?: Json;
          is_active?: boolean;
          last_tested_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          organization_id?: string;
          data_source_id?: string;
          version?: number;
          frequency?: Database["public"]["Enums"]["schedule_frequency"];
          cron_expression?: string | null;
          validation_config?: Json;
          error_handling_config?: Json;
          is_active?: boolean;
          last_tested_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      source_field_mappings: {
        Row: {
          id: string;
          integration_configuration_id: string;
          source_entity: string;
          source_field: string;
          target_table: string;
          target_column: string;
          transform_expression: string | null;
          is_required: boolean;
          created_at: string;
        };
        Insert: {
          id?: string;
          integration_configuration_id: string;
          source_entity: string;
          source_field: string;
          target_table: string;
          target_column: string;
          transform_expression?: string | null;
          is_required?: boolean;
          created_at?: string;
        };
        Update: {
          id?: string;
          integration_configuration_id?: string;
          source_entity?: string;
          source_field?: string;
          target_table?: string;
          target_column?: string;
          transform_expression?: string | null;
          is_required?: boolean;
          created_at?: string;
        };
        Relationships: [];
      };
      ingestion_jobs: {
        Row: {
          id: string;
          organization_id: string;
          data_source_id: string;
          integration_configuration_id: string | null;
          job_type: string;
          status: Database["public"]["Enums"]["job_status"];
          triggered_by: string | null;
          started_at: string | null;
          finished_at: string | null;
          published_at: string | null;
          processing_window_start: string | null;
          processing_window_end: string | null;
          rows_received: number;
          rows_processed: number;
          rows_rejected: number;
          error_details: Json;
          created_at: string;
        };
        Insert: {
          id?: string;
          organization_id: string;
          data_source_id: string;
          integration_configuration_id?: string | null;
          job_type: string;
          status?: Database["public"]["Enums"]["job_status"];
          triggered_by?: string | null;
          started_at?: string | null;
          finished_at?: string | null;
          published_at?: string | null;
          processing_window_start?: string | null;
          processing_window_end?: string | null;
          rows_received?: number;
          rows_processed?: number;
          rows_rejected?: number;
          error_details?: Json;
          created_at?: string;
        };
        Update: {
          id?: string;
          organization_id?: string;
          data_source_id?: string;
          integration_configuration_id?: string | null;
          job_type?: string;
          status?: Database["public"]["Enums"]["job_status"];
          triggered_by?: string | null;
          started_at?: string | null;
          finished_at?: string | null;
          published_at?: string | null;
          processing_window_start?: string | null;
          processing_window_end?: string | null;
          rows_received?: number;
          rows_processed?: number;
          rows_rejected?: number;
          error_details?: Json;
          created_at?: string;
        };
        Relationships: [];
      };
      data_quality_rules: {
        Row: {
          id: string;
          organization_id: string;
          name: string;
          target_table: string;
          rule_type: string;
          severity: Database["public"]["Enums"]["data_quality_severity"];
          rule_definition: Json;
          is_active: boolean;
          created_by: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          organization_id: string;
          name: string;
          target_table: string;
          rule_type: string;
          severity?: Database["public"]["Enums"]["data_quality_severity"];
          rule_definition?: Json;
          is_active?: boolean;
          created_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          organization_id?: string;
          name?: string;
          target_table?: string;
          rule_type?: string;
          severity?: Database["public"]["Enums"]["data_quality_severity"];
          rule_definition?: Json;
          is_active?: boolean;
          created_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      data_quality_issues: {
        Row: {
          id: string;
          organization_id: string;
          rule_id: string;
          ingestion_job_id: string | null;
          affected_table: string;
          record_primary_key: string | null;
          severity: Database["public"]["Enums"]["data_quality_severity"];
          issue_status: string;
          detected_at: string;
          resolved_at: string | null;
          details: Json;
        };
        Insert: {
          id?: string;
          organization_id: string;
          rule_id: string;
          ingestion_job_id?: string | null;
          affected_table: string;
          record_primary_key?: string | null;
          severity: Database["public"]["Enums"]["data_quality_severity"];
          issue_status?: string;
          detected_at?: string;
          resolved_at?: string | null;
          details?: Json;
        };
        Update: {
          id?: string;
          organization_id?: string;
          rule_id?: string;
          ingestion_job_id?: string | null;
          affected_table?: string;
          record_primary_key?: string | null;
          severity?: Database["public"]["Enums"]["data_quality_severity"];
          issue_status?: string;
          detected_at?: string;
          resolved_at?: string | null;
          details?: Json;
        };
        Relationships: [];
      };
      patients: {
        Row: {
          id: string;
          organization_id: string;
          primary_facility_id: string | null;
          patient_identifier: string;
          medical_record_number: string | null;
          first_name: string | null;
          last_name: string | null;
          date_of_birth: string | null;
          sex: string | null;
          gender_identity: string | null;
          source_system: string | null;
          source_record_id: string | null;
          metadata: Json;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          organization_id: string;
          primary_facility_id?: string | null;
          patient_identifier: string;
          medical_record_number?: string | null;
          first_name?: string | null;
          last_name?: string | null;
          date_of_birth?: string | null;
          sex?: string | null;
          gender_identity?: string | null;
          source_system?: string | null;
          source_record_id?: string | null;
          metadata?: Json;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          organization_id?: string;
          primary_facility_id?: string | null;
          patient_identifier?: string;
          medical_record_number?: string | null;
          first_name?: string | null;
          last_name?: string | null;
          date_of_birth?: string | null;
          sex?: string | null;
          gender_identity?: string | null;
          source_system?: string | null;
          source_record_id?: string | null;
          metadata?: Json;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      clinical_encounters: {
        Row: {
          id: string;
          organization_id: string;
          patient_id: string;
          facility_id: string | null;
          department_id: string | null;
          encounter_number: string;
          encounter_type: string;
          status: string | null;
          admission_at: string | null;
          discharge_at: string | null;
          attending_provider: string | null;
          diagnosis_codes: string[];
          procedure_codes: string[];
          source_system: string | null;
          source_record_id: string | null;
          metadata: Json;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          organization_id: string;
          patient_id: string;
          facility_id?: string | null;
          department_id?: string | null;
          encounter_number: string;
          encounter_type: string;
          status?: string | null;
          admission_at?: string | null;
          discharge_at?: string | null;
          attending_provider?: string | null;
          diagnosis_codes?: string[];
          procedure_codes?: string[];
          source_system?: string | null;
          source_record_id?: string | null;
          metadata?: Json;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          organization_id?: string;
          patient_id?: string;
          facility_id?: string | null;
          department_id?: string | null;
          encounter_number?: string;
          encounter_type?: string;
          status?: string | null;
          admission_at?: string | null;
          discharge_at?: string | null;
          attending_provider?: string | null;
          diagnosis_codes?: string[];
          procedure_codes?: string[];
          source_system?: string | null;
          source_record_id?: string | null;
          metadata?: Json;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      financial_transactions: {
        Row: {
          id: string;
          organization_id: string;
          patient_id: string | null;
          encounter_id: string | null;
          facility_id: string | null;
          department_id: string | null;
          transaction_type: string;
          transaction_date: string;
          posting_date: string | null;
          account_code: string | null;
          account_name: string | null;
          payer_name: string | null;
          amount: number;
          currency_code: string;
          revenue_code: string | null;
          status: string | null;
          source_system: string | null;
          source_record_id: string | null;
          metadata: Json;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          organization_id: string;
          patient_id?: string | null;
          encounter_id?: string | null;
          facility_id?: string | null;
          department_id?: string | null;
          transaction_type: string;
          transaction_date: string;
          posting_date?: string | null;
          account_code?: string | null;
          account_name?: string | null;
          payer_name?: string | null;
          amount: number;
          currency_code?: string;
          revenue_code?: string | null;
          status?: string | null;
          source_system?: string | null;
          source_record_id?: string | null;
          metadata?: Json;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          organization_id?: string;
          patient_id?: string | null;
          encounter_id?: string | null;
          facility_id?: string | null;
          department_id?: string | null;
          transaction_type?: string;
          transaction_date?: string;
          posting_date?: string | null;
          account_code?: string | null;
          account_name?: string | null;
          payer_name?: string | null;
          amount?: number;
          currency_code?: string;
          revenue_code?: string | null;
          status?: string | null;
          source_system?: string | null;
          source_record_id?: string | null;
          metadata?: Json;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      budget_items: {
        Row: {
          id: string;
          organization_id: string;
          facility_id: string | null;
          department_id: string | null;
          service_line_id: string | null;
          fiscal_year: number;
          fiscal_period: number | null;
          scenario_name: string;
          account_code: string;
          account_name: string | null;
          amount: number;
          source_system: string | null;
          metadata: Json;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          organization_id: string;
          facility_id?: string | null;
          department_id?: string | null;
          service_line_id?: string | null;
          fiscal_year: number;
          fiscal_period?: number | null;
          scenario_name?: string;
          account_code: string;
          account_name?: string | null;
          amount: number;
          source_system?: string | null;
          metadata?: Json;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          organization_id?: string;
          facility_id?: string | null;
          department_id?: string | null;
          service_line_id?: string | null;
          fiscal_year?: number;
          fiscal_period?: number | null;
          scenario_name?: string;
          account_code?: string;
          account_name?: string | null;
          amount?: number;
          source_system?: string | null;
          metadata?: Json;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      kpi_definitions: {
        Row: {
          id: string;
          organization_id: string;
          code: string;
          name: string;
          domain: string;
          description: string | null;
          formula_expression: string;
          numerator_label: string | null;
          denominator_label: string | null;
          unit_of_measure: string | null;
          aggregation_grain: string | null;
          benchmark_definition: Json;
          target_definition: Json;
          version: number;
          effective_from: string | null;
          effective_to: string | null;
          is_active: boolean;
          created_by: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          organization_id: string;
          code: string;
          name: string;
          domain: string;
          description?: string | null;
          formula_expression: string;
          numerator_label?: string | null;
          denominator_label?: string | null;
          unit_of_measure?: string | null;
          aggregation_grain?: string | null;
          benchmark_definition?: Json;
          target_definition?: Json;
          version?: number;
          effective_from?: string | null;
          effective_to?: string | null;
          is_active?: boolean;
          created_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          organization_id?: string;
          code?: string;
          name?: string;
          domain?: string;
          description?: string | null;
          formula_expression?: string;
          numerator_label?: string | null;
          denominator_label?: string | null;
          unit_of_measure?: string | null;
          aggregation_grain?: string | null;
          benchmark_definition?: Json;
          target_definition?: Json;
          version?: number;
          effective_from?: string | null;
          effective_to?: string | null;
          is_active?: boolean;
          created_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      metrics: {
        Row: {
          id: string;
          organization_id: string;
          kpi_definition_id: string | null;
          code: string;
          name: string;
          domain: string;
          description: string | null;
          metric_type: string;
          value_data_type: string;
          dimensions_schema: Json;
          is_active: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          organization_id: string;
          kpi_definition_id?: string | null;
          code: string;
          name: string;
          domain: string;
          description?: string | null;
          metric_type: string;
          value_data_type?: string;
          dimensions_schema?: Json;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          organization_id?: string;
          kpi_definition_id?: string | null;
          code?: string;
          name?: string;
          domain?: string;
          description?: string | null;
          metric_type?: string;
          value_data_type?: string;
          dimensions_schema?: Json;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      metric_values: {
        Row: {
          id: string;
          organization_id: string;
          metric_id: string;
          kpi_definition_id: string | null;
          facility_id: string | null;
          department_id: string | null;
          service_line_id: string | null;
          ingestion_job_id: string | null;
          period_start: string | null;
          period_end: string | null;
          as_of_date: string;
          value_numeric: number | null;
          value_text: string | null;
          value_json: Json | null;
          target_value: number | null;
          benchmark_value: number | null;
          variance_value: number | null;
          status: Database["public"]["Enums"]["metric_value_status"];
          lineage: Json;
          created_at: string;
        };
        Insert: {
          id?: string;
          organization_id: string;
          metric_id: string;
          kpi_definition_id?: string | null;
          facility_id?: string | null;
          department_id?: string | null;
          service_line_id?: string | null;
          ingestion_job_id?: string | null;
          period_start?: string | null;
          period_end?: string | null;
          as_of_date: string;
          value_numeric?: number | null;
          value_text?: string | null;
          value_json?: Json | null;
          target_value?: number | null;
          benchmark_value?: number | null;
          variance_value?: number | null;
          status?: Database["public"]["Enums"]["metric_value_status"];
          lineage?: Json;
          created_at?: string;
        };
        Update: {
          id?: string;
          organization_id?: string;
          metric_id?: string;
          kpi_definition_id?: string | null;
          facility_id?: string | null;
          department_id?: string | null;
          service_line_id?: string | null;
          ingestion_job_id?: string | null;
          period_start?: string | null;
          period_end?: string | null;
          as_of_date?: string;
          value_numeric?: number | null;
          value_text?: string | null;
          value_json?: Json | null;
          target_value?: number | null;
          benchmark_value?: number | null;
          variance_value?: number | null;
          status?: Database["public"]["Enums"]["metric_value_status"];
          lineage?: Json;
          created_at?: string;
        };
        Relationships: [];
      };
      dashboards: {
        Row: {
          id: string;
          organization_id: string;
          owner_user_id: string | null;
          audience_role_id: string | null;
          name: string;
          slug: string;
          description: string | null;
          visibility: Database["public"]["Enums"]["asset_visibility"];
          is_default: boolean;
          filters_config: Json;
          layout_config: Json;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          organization_id: string;
          owner_user_id?: string | null;
          audience_role_id?: string | null;
          name: string;
          slug: string;
          description?: string | null;
          visibility?: Database["public"]["Enums"]["asset_visibility"];
          is_default?: boolean;
          filters_config?: Json;
          layout_config?: Json;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          organization_id?: string;
          owner_user_id?: string | null;
          audience_role_id?: string | null;
          name?: string;
          slug?: string;
          description?: string | null;
          visibility?: Database["public"]["Enums"]["asset_visibility"];
          is_default?: boolean;
          filters_config?: Json;
          layout_config?: Json;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      reports: {
        Row: {
          id: string;
          organization_id: string;
          owner_user_id: string | null;
          name: string;
          slug: string;
          description: string | null;
          visibility: Database["public"]["Enums"]["asset_visibility"];
          definition: Json;
          dataset_config: Json;
          visualization_config: Json;
          published_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          organization_id: string;
          owner_user_id?: string | null;
          name: string;
          slug: string;
          description?: string | null;
          visibility?: Database["public"]["Enums"]["asset_visibility"];
          definition?: Json;
          dataset_config?: Json;
          visualization_config?: Json;
          published_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          organization_id?: string;
          owner_user_id?: string | null;
          name?: string;
          slug?: string;
          description?: string | null;
          visibility?: Database["public"]["Enums"]["asset_visibility"];
          definition?: Json;
          dataset_config?: Json;
          visualization_config?: Json;
          published_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      dashboard_widgets: {
        Row: {
          id: string;
          dashboard_id: string;
          metric_id: string | null;
          report_id: string | null;
          title: string;
          widget_type: string;
          position_x: number;
          position_y: number;
          width: number;
          height: number;
          config: Json;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          dashboard_id: string;
          metric_id?: string | null;
          report_id?: string | null;
          title: string;
          widget_type: string;
          position_x?: number;
          position_y?: number;
          width?: number;
          height?: number;
          config?: Json;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          dashboard_id?: string;
          metric_id?: string | null;
          report_id?: string | null;
          title?: string;
          widget_type?: string;
          position_x?: number;
          position_y?: number;
          width?: number;
          height?: number;
          config?: Json;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      report_schedules: {
        Row: {
          id: string;
          organization_id: string;
          report_id: string;
          frequency: Database["public"]["Enums"]["schedule_frequency"];
          cron_expression: string | null;
          delivery_channels: Database["public"]["Enums"]["notification_channel"][];
          recipient_config: Json;
          format: Database["public"]["Enums"]["report_format"];
          is_active: boolean;
          last_run_at: string | null;
          next_run_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          organization_id: string;
          report_id: string;
          frequency?: Database["public"]["Enums"]["schedule_frequency"];
          cron_expression?: string | null;
          delivery_channels?: Database["public"]["Enums"]["notification_channel"][];
          recipient_config?: Json;
          format?: Database["public"]["Enums"]["report_format"];
          is_active?: boolean;
          last_run_at?: string | null;
          next_run_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          organization_id?: string;
          report_id?: string;
          frequency?: Database["public"]["Enums"]["schedule_frequency"];
          cron_expression?: string | null;
          delivery_channels?: Database["public"]["Enums"]["notification_channel"][];
          recipient_config?: Json;
          format?: Database["public"]["Enums"]["report_format"];
          is_active?: boolean;
          last_run_at?: string | null;
          next_run_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      report_runs: {
        Row: {
          id: string;
          organization_id: string;
          report_id: string;
          report_schedule_id: string | null;
          triggered_by: string | null;
          format: Database["public"]["Enums"]["report_format"];
          status: Database["public"]["Enums"]["job_status"];
          started_at: string | null;
          completed_at: string | null;
          output_path: string | null;
          row_count: number | null;
          error_details: Json;
          created_at: string;
        };
        Insert: {
          id?: string;
          organization_id: string;
          report_id: string;
          report_schedule_id?: string | null;
          triggered_by?: string | null;
          format?: Database["public"]["Enums"]["report_format"];
          status?: Database["public"]["Enums"]["job_status"];
          started_at?: string | null;
          completed_at?: string | null;
          output_path?: string | null;
          row_count?: number | null;
          error_details?: Json;
          created_at?: string;
        };
        Update: {
          id?: string;
          organization_id?: string;
          report_id?: string;
          report_schedule_id?: string | null;
          triggered_by?: string | null;
          format?: Database["public"]["Enums"]["report_format"];
          status?: Database["public"]["Enums"]["job_status"];
          started_at?: string | null;
          completed_at?: string | null;
          output_path?: string | null;
          row_count?: number | null;
          error_details?: Json;
          created_at?: string;
        };
        Relationships: [];
      };
      scheduled_jobs: {
        Row: {
          id: string;
          organization_id: string;
          job_category: string;
          job_name: string;
          related_entity_type: string | null;
          related_entity_id: string | null;
          frequency: Database["public"]["Enums"]["schedule_frequency"];
          cron_expression: string | null;
          config: Json;
          is_active: boolean;
          last_run_at: string | null;
          next_run_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          organization_id: string;
          job_category: string;
          job_name: string;
          related_entity_type?: string | null;
          related_entity_id?: string | null;
          frequency: Database["public"]["Enums"]["schedule_frequency"];
          cron_expression?: string | null;
          config?: Json;
          is_active?: boolean;
          last_run_at?: string | null;
          next_run_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          organization_id?: string;
          job_category?: string;
          job_name?: string;
          related_entity_type?: string | null;
          related_entity_id?: string | null;
          frequency?: Database["public"]["Enums"]["schedule_frequency"];
          cron_expression?: string | null;
          config?: Json;
          is_active?: boolean;
          last_run_at?: string | null;
          next_run_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      benchmarks: {
        Row: {
          id: string;
          organization_id: string;
          metric_id: string | null;
          kpi_definition_id: string | null;
          name: string;
          source_type: Database["public"]["Enums"]["benchmark_source_type"];
          domain: string;
          comparison_method: string | null;
          value_numeric: number | null;
          value_json: Json | null;
          source_reference: string | null;
          benchmark_start: string | null;
          benchmark_end: string | null;
          version: number;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          organization_id: string;
          metric_id?: string | null;
          kpi_definition_id?: string | null;
          name: string;
          source_type?: Database["public"]["Enums"]["benchmark_source_type"];
          domain: string;
          comparison_method?: string | null;
          value_numeric?: number | null;
          value_json?: Json | null;
          source_reference?: string | null;
          benchmark_start?: string | null;
          benchmark_end?: string | null;
          version?: number;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          organization_id?: string;
          metric_id?: string | null;
          kpi_definition_id?: string | null;
          name?: string;
          source_type?: Database["public"]["Enums"]["benchmark_source_type"];
          domain?: string;
          comparison_method?: string | null;
          value_numeric?: number | null;
          value_json?: Json | null;
          source_reference?: string | null;
          benchmark_start?: string | null;
          benchmark_end?: string | null;
          version?: number;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      targets: {
        Row: {
          id: string;
          organization_id: string;
          metric_id: string | null;
          kpi_definition_id: string | null;
          scope_level: Database["public"]["Enums"]["scope_level"];
          facility_id: string | null;
          department_id: string | null;
          service_line_id: string | null;
          owner_user_id: string | null;
          period_start: string;
          period_end: string;
          target_value: number;
          tolerance_percent: number | null;
          notes: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          organization_id: string;
          metric_id?: string | null;
          kpi_definition_id?: string | null;
          scope_level?: Database["public"]["Enums"]["scope_level"];
          facility_id?: string | null;
          department_id?: string | null;
          service_line_id?: string | null;
          owner_user_id?: string | null;
          period_start: string;
          period_end: string;
          target_value: number;
          tolerance_percent?: number | null;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          organization_id?: string;
          metric_id?: string | null;
          kpi_definition_id?: string | null;
          scope_level?: Database["public"]["Enums"]["scope_level"];
          facility_id?: string | null;
          department_id?: string | null;
          service_line_id?: string | null;
          owner_user_id?: string | null;
          period_start?: string;
          period_end?: string;
          target_value?: number;
          tolerance_percent?: number | null;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      alert_rules: {
        Row: {
          id: string;
          organization_id: string;
          metric_id: string | null;
          kpi_definition_id: string | null;
          data_quality_rule_id: string | null;
          facility_id: string | null;
          department_id: string | null;
          name: string;
          description: string | null;
          severity: Database["public"]["Enums"]["alert_severity"];
          condition_expression: string;
          threshold_config: Json;
          evaluation_window: Json;
          is_active: boolean;
          created_by: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          organization_id: string;
          metric_id?: string | null;
          kpi_definition_id?: string | null;
          data_quality_rule_id?: string | null;
          facility_id?: string | null;
          department_id?: string | null;
          name: string;
          description?: string | null;
          severity?: Database["public"]["Enums"]["alert_severity"];
          condition_expression: string;
          threshold_config?: Json;
          evaluation_window?: Json;
          is_active?: boolean;
          created_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          organization_id?: string;
          metric_id?: string | null;
          kpi_definition_id?: string | null;
          data_quality_rule_id?: string | null;
          facility_id?: string | null;
          department_id?: string | null;
          name?: string;
          description?: string | null;
          severity?: Database["public"]["Enums"]["alert_severity"];
          condition_expression?: string;
          threshold_config?: Json;
          evaluation_window?: Json;
          is_active?: boolean;
          created_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      alerts: {
        Row: {
          id: string;
          organization_id: string;
          rule_id: string;
          metric_value_id: string | null;
          severity: Database["public"]["Enums"]["alert_severity"];
          state: Database["public"]["Enums"]["alert_state"];
          title: string;
          message: string;
          context: Json;
          triggered_at: string;
          acknowledged_at: string | null;
          resolved_at: string | null;
          acknowledged_by: string | null;
          resolved_by: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          organization_id: string;
          rule_id: string;
          metric_value_id?: string | null;
          severity: Database["public"]["Enums"]["alert_severity"];
          state?: Database["public"]["Enums"]["alert_state"];
          title: string;
          message: string;
          context?: Json;
          triggered_at?: string;
          acknowledged_at?: string | null;
          resolved_at?: string | null;
          acknowledged_by?: string | null;
          resolved_by?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          organization_id?: string;
          rule_id?: string;
          metric_value_id?: string | null;
          severity?: Database["public"]["Enums"]["alert_severity"];
          state?: Database["public"]["Enums"]["alert_state"];
          title?: string;
          message?: string;
          context?: Json;
          triggered_at?: string;
          acknowledged_at?: string | null;
          resolved_at?: string | null;
          acknowledged_by?: string | null;
          resolved_by?: string | null;
          created_at?: string;
        };
        Relationships: [];
      };
      alert_recipients: {
        Row: {
          id: string;
          alert_rule_id: string;
          user_id: string | null;
          role_id: string | null;
          channel: Database["public"]["Enums"]["notification_channel"];
          escalation_delay_minutes: number | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          alert_rule_id: string;
          user_id?: string | null;
          role_id?: string | null;
          channel?: Database["public"]["Enums"]["notification_channel"];
          escalation_delay_minutes?: number | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          alert_rule_id?: string;
          user_id?: string | null;
          role_id?: string | null;
          channel?: Database["public"]["Enums"]["notification_channel"];
          escalation_delay_minutes?: number | null;
          created_at?: string;
        };
        Relationships: [];
      };
      notifications: {
        Row: {
          id: string;
          organization_id: string;
          alert_id: string | null;
          recipient_user_id: string;
          related_entity_type: string | null;
          related_entity_id: string | null;
          channel: Database["public"]["Enums"]["notification_channel"];
          status: Database["public"]["Enums"]["notification_status"];
          subject: string | null;
          body: string | null;
          payload: Json;
          sent_at: string | null;
          read_at: string | null;
          error_message: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          organization_id: string;
          alert_id?: string | null;
          recipient_user_id: string;
          related_entity_type?: string | null;
          related_entity_id?: string | null;
          channel: Database["public"]["Enums"]["notification_channel"];
          status?: Database["public"]["Enums"]["notification_status"];
          subject?: string | null;
          body?: string | null;
          payload?: Json;
          sent_at?: string | null;
          read_at?: string | null;
          error_message?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          organization_id?: string;
          alert_id?: string | null;
          recipient_user_id?: string;
          related_entity_type?: string | null;
          related_entity_id?: string | null;
          channel?: Database["public"]["Enums"]["notification_channel"];
          status?: Database["public"]["Enums"]["notification_status"];
          subject?: string | null;
          body?: string | null;
          payload?: Json;
          sent_at?: string | null;
          read_at?: string | null;
          error_message?: string | null;
          created_at?: string;
        };
        Relationships: [];
      };
      audit_logs: {
        Row: {
          id: number;
          organization_id: string | null;
          actor_user_id: string | null;
          actor_type: Database["public"]["Enums"]["audit_actor_type"];
          action: string;
          entity_type: string;
          entity_id: string | null;
          scope_level: Database["public"]["Enums"]["scope_level"];
          facility_id: string | null;
          department_id: string | null;
          ip_address: string | null;
          user_agent: string | null;
          request_id: string | null;
          metadata: Json;
          created_at: string;
        };
        Insert: {
          id?: number;
          organization_id?: string | null;
          actor_user_id?: string | null;
          actor_type?: Database["public"]["Enums"]["audit_actor_type"];
          action: string;
          entity_type: string;
          entity_id?: string | null;
          scope_level?: Database["public"]["Enums"]["scope_level"];
          facility_id?: string | null;
          department_id?: string | null;
          ip_address?: string | null;
          user_agent?: string | null;
          request_id?: string | null;
          metadata?: Json;
          created_at?: string;
        };
        Update: {
          id?: number;
          organization_id?: string | null;
          actor_user_id?: string | null;
          actor_type?: Database["public"]["Enums"]["audit_actor_type"];
          action?: string;
          entity_type?: string;
          entity_id?: string | null;
          scope_level?: Database["public"]["Enums"]["scope_level"];
          facility_id?: string | null;
          department_id?: string | null;
          ip_address?: string | null;
          user_agent?: string | null;
          request_id?: string | null;
          metadata?: Json;
          created_at?: string;
        };
        Relationships: [];
      };
      forecast_scenarios: {
        Row: {
          id: string;
          organization_id: string;
          baseline_scenario_id: string | null;
          created_by: string | null;
          scope_level: Database["public"]["Enums"]["scope_level"];
          facility_id: string | null;
          department_id: string | null;
          service_line_id: string | null;
          name: string;
          description: string | null;
          version: number;
          status: string;
          starts_on: string | null;
          ends_on: string | null;
          assumptions_summary: Json;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          organization_id: string;
          baseline_scenario_id?: string | null;
          created_by?: string | null;
          scope_level?: Database["public"]["Enums"]["scope_level"];
          facility_id?: string | null;
          department_id?: string | null;
          service_line_id?: string | null;
          name: string;
          description?: string | null;
          version?: number;
          status?: string;
          starts_on?: string | null;
          ends_on?: string | null;
          assumptions_summary?: Json;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          organization_id?: string;
          baseline_scenario_id?: string | null;
          created_by?: string | null;
          scope_level?: Database["public"]["Enums"]["scope_level"];
          facility_id?: string | null;
          department_id?: string | null;
          service_line_id?: string | null;
          name?: string;
          description?: string | null;
          version?: number;
          status?: string;
          starts_on?: string | null;
          ends_on?: string | null;
          assumptions_summary?: Json;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      forecast_assumptions: {
        Row: {
          id: string;
          scenario_id: string;
          assumption_key: string;
          assumption_value: Json;
          notes: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          scenario_id: string;
          assumption_key: string;
          assumption_value?: Json;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          scenario_id?: string;
          assumption_key?: string;
          assumption_value?: Json;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      annotations: {
        Row: {
          id: string;
          organization_id: string;
          author_user_id: string | null;
          related_entity_type: string;
          related_entity_id: string;
          visibility: Database["public"]["Enums"]["asset_visibility"];
          content: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          organization_id: string;
          author_user_id?: string | null;
          related_entity_type: string;
          related_entity_id: string;
          visibility?: Database["public"]["Enums"]["asset_visibility"];
          content: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          organization_id?: string;
          author_user_id?: string | null;
          related_entity_type?: string;
          related_entity_id?: string;
          visibility?: Database["public"]["Enums"]["asset_visibility"];
          content?: string;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      insights: {
        Row: {
          id: string;
          organization_id: string;
          created_by_user_id: string | null;
          title: string;
          summary: string;
          domain: string;
          related_entity_type: string | null;
          related_entity_id: string | null;
          confidence: number | null;
          insight_payload: Json;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          organization_id: string;
          created_by_user_id?: string | null;
          title: string;
          summary: string;
          domain: string;
          related_entity_type?: string | null;
          related_entity_id?: string | null;
          confidence?: number | null;
          insight_payload?: Json;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          organization_id?: string;
          created_by_user_id?: string | null;
          title?: string;
          summary?: string;
          domain?: string;
          related_entity_type?: string | null;
          related_entity_id?: string | null;
          confidence?: number | null;
          insight_payload?: Json;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      predictions: {
        Row: {
          id: string;
          organization_id: string;
          forecast_scenario_id: string | null;
          created_by_user_id: string | null;
          prediction_type: Database["public"]["Enums"]["prediction_type"];
          model_name: string;
          model_version: string | null;
          target_entity_type: string | null;
          target_entity_id: string | null;
          prediction_for: string | null;
          output_summary: Json;
          confidence: number | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          organization_id: string;
          forecast_scenario_id?: string | null;
          created_by_user_id?: string | null;
          prediction_type: Database["public"]["Enums"]["prediction_type"];
          model_name: string;
          model_version?: string | null;
          target_entity_type?: string | null;
          target_entity_id?: string | null;
          prediction_for?: string | null;
          output_summary?: Json;
          confidence?: number | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          organization_id?: string;
          forecast_scenario_id?: string | null;
          created_by_user_id?: string | null;
          prediction_type?: Database["public"]["Enums"]["prediction_type"];
          model_name?: string;
          model_version?: string | null;
          target_entity_type?: string | null;
          target_entity_id?: string | null;
          prediction_for?: string | null;
          output_summary?: Json;
          confidence?: number | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      model_results: {
        Row: {
          id: string;
          organization_id: string;
          prediction_id: string;
          result_key: string;
          result_value: Json;
          rank_order: number | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          organization_id: string;
          prediction_id: string;
          result_key: string;
          result_value?: Json;
          rank_order?: number | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          organization_id?: string;
          prediction_id?: string;
          result_key?: string;
          result_value?: Json;
          rank_order?: number | null;
          created_at?: string;
        };
        Relationships: [];
      };
    };
    Views: Record<string, never>;
    Functions: Record<string, never>;
    Enums: {
      organization_status: "draft" | "active" | "inactive";
      user_account_status: "pending" | "active" | "inactive" | "suspended";
      scope_level: "global" | "organization" | "facility" | "department" | "service_line";
      data_source_type: "api" | "database" | "flat_file" | "scheduled_import" | "fhir" | "hl7" | "sftp";
      connection_status: "pending" | "connected" | "failed" | "disabled";
      job_status: "queued" | "running" | "succeeded" | "failed" | "cancelled" | "partial";
      metric_value_status: "draft" | "published" | "superseded";
      asset_visibility: "private" | "shared" | "role_based";
      report_format: "pdf" | "csv" | "xlsx";
      alert_severity: "info" | "warning" | "critical";
      alert_state: "new" | "acknowledged" | "resolved" | "dismissed" | "closed";
      notification_channel: "in_app" | "email" | "sms" | "webhook";
      notification_status: "pending" | "sent" | "delivered" | "failed" | "read";
      data_quality_severity: "info" | "warning" | "error" | "critical";
      audit_actor_type: "user" | "service" | "system";
      benchmark_source_type: "internal" | "external" | "licensed" | "customer_provided";
      schedule_frequency: "once" | "hourly" | "daily" | "weekly" | "monthly" | "quarterly";
      prediction_type: "forecast" | "anomaly" | "insight" | "classification" | "regression";
    };
    CompositeTypes: Record<string, never>;
  };
}
